services:
  postgres:
    image: postgres:18
    container_name: moodle-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
    
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build: .
    container_name: moodle-backend

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MOODLE_TOKEN_KEY: ${MOODLE_TOKEN_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      REGISTRATION_INVITE_CODE: ${REGISTRATION_INVITE_CODE}


    depends_on:
      postgres:
        condition: service_healthy
    
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000

    container_name:
      moodle-frontend

    ports:
      - "5173:80"
    
    depends_on:
      - backend


volumes:
  postgres_data: