"""add moodle connections

Revision ID: 4a5a94e91045
Revises: 7e10a86679c2
Create Date: 2026-09-12 13:18:14.538420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5a94e91045'
down_revision: Union[str, Sequence[str], None] = '7e10a86679c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moodle_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('used_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('encrypted_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['used_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('used_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moodle_connections')
    # ### end Alembic commands ###
