"""make assignments unique per course

Revision ID: a3adb7396779
Revises: b83045c638fe
Create Date: 2026-09-13 23:30:19.296260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3adb7396779'
down_revision: Union[str, Sequence[str], None] = 'b83045c638fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # assignemts_moodle_id_key is the name of the existing unique constraint on the "moodle_id" column in the "assignments" table. 
    # This constraint ensures that each assignment has a unique Moodle ID across all courses, which is not desired in this case.
    # uq_assignements_course_moodle is the name of the new unique constraint that combines the "course_id" and "moodle_id" columns in the "assignments" table.
    op.drop_constraint(op.f('assignments_moodle_id_key'), 'assignments', type_='unique')
    op.create_unique_constraint('uq_assignements_course_moodle', 'assignments', ['course_id', 'moodle_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_assignements_course_moodle', 'assignments', type_='unique')
    op.create_unique_constraint(op.f('assignments_moodle_id_key'), 'assignments', ['moodle_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
