"""make courses unique per user

Revision ID: b83045c638fe
Revises: 0450d8bdc7f0
Create Date: 2026-09-13 22:46:21.251372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83045c638fe'
down_revision: Union[str, Sequence[str], None] = '0450d8bdc7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the existing unique constraint on the "moodle_id" column in the "courses" table.
    # This constraint ensures that each course has a unique Moodle ID across all users, which is not desired in this case.
    # Create a new unique constraint that combines the "user_id" and "moodle_id" columns in the "courses" table.
    # uq_courses_user_moodle is the name of the new unique constraint, and it ensures that each user can have unique courses based on their Moodle ID.
    op.drop_constraint(op.f('courses_moodle_id_key'), 'courses', type_='unique')
    op.create_unique_constraint('uq_courses_user_moodle', 'courses', ['user_id', 'moodle_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_courses_user_moodle', 'courses', type_='unique')
    op.create_unique_constraint(op.f('courses_moodle_id_key'), 'courses', ['moodle_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
